"""Diagnostic (not proof): verify
(1) Exact identity: for uniform ordered set-partition of a K-set into cells of
    fixed sizes n_0..n_{s-1}, and characters psi_0..psi_{s-1} mod q,
      E[prod_s psi_s(W_s)] = [x^n] prod_ell (sum_s x_s psi_s(ell)) / multinomial(K;n)
(2) Contour/decay bound:
      |E[...]| <= (multinomial * prod rho_s^{n_s})^{-1} * max_{|x_s|=rho_s} prod_ell |sum x_s psi_s(ell)|
    and the analytic exponent bound
      max_theta prod_ell |...| <= exp(- sum_{s<s'} (n_s n_{s'}/K) (1 - t_{psi_s bar psi_{s'}}))
    where t_chi = |sum_ell chi(ell)|/K.
Small case: q=11 prime modulus, K=7 'block primes' = distinct units mod 11,
cells (3,2,2). Exhaustive enumeration of partitions.
"""
import itertools, math, cmath, random

q = 11
# multiplicative group mod 11 generated by 2
g = 2
# discrete log table
dlog = {}
x = 1
for e in range(q-1):
    dlog[x] = e
    x = (x*g) % q

def char(j):  # character chi_j(u) = e(2pi i j dlog(u)/(q-1))
    return lambda u, j=j: cmath.exp(complex(0, 2*math.pi*j*dlog[u]/(q-1)))

ells = [2, 3, 5, 6, 7, 8, 10]  # 7 distinct units mod 11
K = len(ells)
sizes = (3, 2, 2)
chars_idx = (1, 9, 4)  # psi_0 = chi_3, psi_1 = chi_5, psi_2 = chi_0 (principal)
psis = [char(j) for j in chars_idx]

# (1) direct enumeration
tot = 0
count = 0
idx = list(range(K))
for c0 in itertools.combinations(idx, sizes[0]):
    rest = [i for i in idx if i not in c0]
    for c1 in itertools.combinations(rest, sizes[1]):
        c2 = [i for i in rest if i not in c1]
        val = 1+0j
        for cell, psi in zip((c0, c1, tuple(c2)), psis):
            for i in cell:
                val *= psi(ells[i])
        tot += val
        count += 1
E_direct = tot / count
mult = math.factorial(K)//(math.factorial(sizes[0])*math.factorial(sizes[1])*math.factorial(sizes[2]))
assert count == mult, (count, mult)

# (1b) coefficient extraction: [x0^3 x1^2 x2^2] prod_ell (x0 psi0(l) + x1 psi1(l) + x2 psi2(l))
# expand polynomial in 3 vars, degrees up to sizes
from collections import defaultdict
poly = defaultdict(complex)
poly[(0,0,0)] = 1
for l in ells:
    new = defaultdict(complex)
    vals = [psi(l) for psi in psis]
    for mono, c in poly.items():
        for s in range(3):
            m2 = list(mono); m2[s] += 1
            new[tuple(m2)] += c * vals[s]
    poly = new
E_coeff = poly[sizes] / mult
print("identity check: direct =", E_direct, " coeff/mult =", E_coeff,
      " |diff| =", abs(E_direct - E_coeff))

# (2) contour bound with rho_s = n_s/K, grid over phases
rhos = [n/K for n in sizes]
pref = 1.0/(mult * math.prod(r**n for r, n in zip(rhos, sizes)))
best = 0.0
G = 24
for t1 in range(G):
    for t2 in range(G):
        th = [0.0, 2*math.pi*t1/G, 2*math.pi*t2/G]
        prod = 1.0
        for l in ells:
            z = sum(r*cmath.exp(complex(0, t))*psi(l) for r, t, psi in zip(rhos, th, psis))
            prod *= abs(z)
        best = max(best, prod)
contour_bound = pref * best
print("contour bound =", contour_bound, " actual |E| =", abs(E_direct),
      " bound holds:", abs(E_direct) <= contour_bound + 1e-12)

# analytic exponent bound on the max
def t_ratio(j1, j2):
    j = (j1 - j2) % (q-1)
    s = sum(cmath.exp(complex(0, 2*math.pi*j*dlog[l]/(q-1))) for l in ells)
    return abs(s)/K
expo = 0.0
for s in range(3):
    for sp in range(s+1, 3):
        expo += sizes[s]*sizes[sp]/K * (1 - t_ratio(chars_idx[s], chars_idx[sp]))
analytic = math.exp(-expo)
print("max_theta prod |...| =", best, " <= exp(-E) =", analytic, ":", best <= analytic + 1e-12)
print("full analytic bound =", pref*analytic, ">= |E|:", abs(E_direct) <= pref*analytic + 1e-12)
