"""Independent judge checks for the V1 reconciliation.

Check 1: Lemma 3.1 (exact partition identity) -- E over uniform ordered set
partitions of prod_s psi_s(prod W_s) equals multinomial-normalized coefficient
extraction of prod_ell (sum_s x_s psi_s(ell)).

Check 2: Lemma 3.2 (contour decay bound) -- |Phi| <= C K^2 exp(-sum_{s<s'}
(n_s n_s'/K)(1 - t_{psi_s bar psi_s'})), with C = 1 tested empirically
(we test the exact Stirling-free form: |Phi| <= exp(-sum ...) / (multinom *
prod rho^n) evaluated exactly, and separately the K^2 prefactor claim).

Check 3: rank-conditioning = uniform ordered set partition on the sigma-path
(direct simulation-free exhaustive check at small K): E_sigma[prod_s psi_s(W_s)]
where W_s are the rank-window contents of a uniform permutation.

Check 4: ledger arithmetic for the binding case (symbolic exponent check).
"""
import itertools, math, cmath
from math import comb, factorial

# ---------- setup: characters mod a prime p on a set of "primes" L ----------
p = 11  # modulus
# multiplicative group mod 11 is cyclic generated by 2
g = 2
# discrete log table
dlog = {}
x = 1
for k in range(p-1):
    dlog[x] = k
    x = (x*g) % p

def char(j, a):
    """character chi_j(a) = e(j * dlog(a)/(p-1))"""
    return cmath.exp(2j*cmath.pi*j*dlog[a % p]/(p-1))

# block "primes": distinct units mod 11 (K=7 of them)
L = [2,3,4,5,6,7,8]
K = len(L)

def check_identity(sizes, js):
    """sizes: cell sizes (sum=K); js: character indices per cell.
    Compare exhaustive E over ordered set partitions with coefficient extraction."""
    m = len(sizes)
    assert sum(sizes) == K and len(js) == m
    # exhaustive: iterate over permutations, split into cells by position
    tot = 0.0 + 0j
    cnt = 0
    for perm in itertools.permutations(L):
        idx = 0
        val = 1.0 + 0j
        for s, n in enumerate(sizes):
            prod = 1
            for a in perm[idx:idx+n]:
                prod = (prod * a) % p
            val *= char(js[s], prod)
            idx += n
        tot += val
        cnt += 1
    lhs = tot/cnt
    # coefficient extraction: [x^n] prod_ell (sum_s x_s chi_{j_s}(ell)) / multinom
    # do polynomial multiplication over multi-index dict
    poly = {tuple([0]*m): 1.0+0j}
    for ell in L:
        newpoly = {}
        for mono, c in poly.items():
            for s in range(m):
                mono2 = list(mono); mono2[s] += 1; mono2 = tuple(mono2)
                newpoly[mono2] = newpoly.get(mono2, 0) + c*char(js[s], ell)
        poly = newpoly
    coeff = poly.get(tuple(sizes), 0)
    multinom = factorial(K)
    for n in sizes: multinom //= factorial(n)
    rhs = coeff/multinom
    return lhs, rhs, abs(lhs-rhs)

def t_ratio(j1, j2):
    """t of ratio character chi_{j1} * conj(chi_{j2}) over L: |sum chi|/K"""
    s = sum(char((j1-j2) % (p-1), ell) for ell in L)
    return abs(s)/K

def check_decay(sizes, js):
    lhs, rhs, err = check_identity(sizes, js)
    m = len(sizes)
    expo = 0.0
    for s in range(m):
        for sp in range(s+1, m):
            expo += (sizes[s]*sizes[sp]/K) * (1 - t_ratio(js[s], js[sp]))
    bound = (K**2) * math.exp(-expo)
    return abs(lhs), bound, abs(lhs) <= bound

print("=== Check 1+3: partition identity (exhaustive over permutations, K=7, mod 11) ===")
cases = [
    ((3,2,2), (1,3,7)),
    ((3,2,2), (0,2,5)),
    ((2,2,3), (4,4,9)),   # repeated character
    ((1,2,4), (2,0,6)),   # micro cell
    ((4,3),   (5,1)),     # two cells
    ((2,1,2,2), (1,2,3,4)),  # four cells
]
for sizes, js in cases:
    lhs, rhs, err = check_identity(sizes, js)
    print(f" sizes={sizes} js={js}: E={lhs:.6f} coeff-extract={rhs:.6f} |err|={err:.2e}")

print("\n=== Check 2: contour/pairwise decay bound |Phi| <= K^2 exp(-sum (n n'/K)(1-t_ratio)) ===")
for sizes, js in cases:
    val, bound, ok = check_decay(sizes, js)
    print(f" sizes={sizes} js={js}: |Phi|={val:.4e} bound={bound:.4e} OK={ok}")

print("\n=== Check 4: binding-case ledger arithmetic (exponents, X -> infinity) ===")
# |T|=1 interior-micro, all-3-sigmas-bad class:
# count ~ K^3 * w0 = X^{3+o(1)} pairs; per-pair bias <= beta^3 * sup|c|^2 * 1
# sup|c| = (qr)^{-1/2} = X^{-2}; two singleton slots -> X^{-4}; 2-slot group -> <=1 (Cauchy-Schwarz)
# contribution(beta) = X^3 * beta^3 * X^{-4} ; target M X^{o(1)} = X^2
import sympy as sp
Xs, betas = sp.symbols('X beta', positive=True)
contrib = Xs**3 * betas**3 * Xs**(-4)
target = Xs**2
# solve contrib = target for beta
sol = sp.solve(sp.Eq(contrib, target), betas)
print(" binding case |T|=1,k=3: contribution = X^3 * beta^3 * X^-4; = X^2 requires beta =", sol)
print("   -> need beta <= X^{1+o(1)}; Lemma 5.1 gives beta <= C X log^3 X  (polylog margin ONLY)")
print("   -> RIGOR's claim 'any beta <= X^{4/3-delta} closes' :")
for expo in [sp.Rational(4,3), 1]:
    c = (Xs**3 * (Xs**expo)**3 * Xs**(-4)).simplify()
    print(f"      beta = X^{expo}: contribution = {c}  (target X^2)")
